/**
 * opencode per-model banner plugin.
 *
 * Renders model-specific ASCII art in place of the default opencode wordmark
 * on the home screen, and a compact banner above the prompt in sessions.
 * Art fallback chain: exact model → model family glob → provider → default.
 *
 * Works in the terminal and the opencode desktop app — both run this same TUI.
 *
 * Home screen: overrides the `home_logo` slot (mode="replace").
 * Session: overrides `session_prompt` slot, wrapping the stock Prompt with a
 * compact single-line banner above it that swaps live on model switch.
 */
/** @jsxImportSource @opentui/solid */
import { createMemo, createSignal, Show, Index, type JSX } from "solid-js"
import type { TuiPlugin, TuiPluginApi, TuiSlotContext } from "@opencode-ai/plugin/tui"

// Per-brand art for opencode banners. GENERATED by /tmp/artgen pipeline
// (official lobe-icons SVGs -> resvg raster -> supersampled half-blocks
// with vertical gradient palettes). Hand-typed art replaced by generated art;
// figlet() name-art is the fallback for unknown models.
// Generated by /tmp/artgen — DO NOT EDIT BY HAND.
// Per-brand smooth gradient half-block art (official brand logos,
// supersampled + density-packed). Data model: runs+colors.

type ArtEntry = {
  lines: string[]
  // Generated smooth art: per-line [paletteIdx, text] segments + shared palette.
  runs?: [number, string][][]
  colors?: string[]
  color?: string
  compact?: string[]
}

type ModelKey = { providerID: string; modelID: string }

// ---------------------------------------------------------------------------
// Generated brand art (official logos → smooth gradient half-blocks)
// ---------------------------------------------------------------------------

const deepseekArt: ArtEntry = {
  color: "#8aa6ff",
  colors: ["#8aa6ff","#809cf7","#7692ef","#6c89e7","#627fdf","#5875d7","#4d6bd0","#4361c8","#3957c0","#2f4eb8","#2544b0","#1b3aa8"],
  runs: [[[2,"▄▄▄▄"],[1,"▄▄▄▄▄▄"],[2,"▄"],[1,"▄"],[2,"██"]],[[2,"████████████████████"],[3,"██"],[2,"███"]],[[3,"██████████████████████"],[4,"██"],[3,"▄▄"],[4,"▄▀█"],[3,"██"]],[[3,"█████████████████████████████"],[4,"█"],[3,"▄▄"],[4,"▄▀"]],[[4,"███████████████████████████████████"],[5,"█"],[4,"▄▄"],[5,"▄▄"]],[[5,"▀▀"],[6,"██"],[5,"██████████████████"],[6,"█▄▄▄▀▀"],[5,"▀▀"],[6,"█"],[5,"████████"]],[[7,"▀"],[6,"▀▀"],[7,"█"],[6,"█████████████▄▄"],[7,"█"],[6,"█"],[7,"█▀"],[6,"▀"],[7,"█"],[6,"████"]],[[7,"▀"],[6,"▀"],[7,"█"],[6,"██████████████"],[7,"█"],[6,"▄▄▄▄▄▄"],[7,"█"],[6,"████"]],[[8,"▀"],[7,"▀"],[8,"█"],[7,"██████████████████████"]],[[8,"▄▄▄▄▄"],[9,"▄▄▀"],[8,"▀"],[9,"█"],[8,"██████████████████"]],[[9,"▄"],[8,"████████"],[9,"██"],[8,"▄▄"],[9,"▄▄▀"],[8,"▀▀"],[9,"█"],[8,"███████████"],[9,"█"]],[[9,"██████████████████████"],[10,"█████"],[9,"▄"],[10,"█▀▀▀▀▀"],[9,"▀▀▀▀▀▀▀"]],[[10,"▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀"],[11,"▀▀▀"]]],
  lines: [
    "▄▄▄▄▄▄▄▄▄▄▄▄██",
    "█████████████████████████",
    "████████████████████████▄▄▄▀███",
    "██████████████████████████████▄▄▄▀",
    "████████████████████████████████████▄▄▄▄",
    "▀▀█████████████████████▄▄▄▀▀▀▀█████████",
    "▀▀▀██████████████▄▄███▀▀█████",
    "▀▀████████████████▄▄▄▄▄▄█████",
    "▀▀███████████████████████",
    "▄▄▄▄▄▄▄▀▀███████████████████",
    "▄██████████▄▄▄▄▀▀▀█████████████",
    "███████████████████████████▄█▀▀▀▀▀▀▀▀▀▀▀▀",
    "▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
  ],
}
const zaiArt: ArtEntry = {
  color: "#7de8fa",
  colors: ["#7de8fa","#73ddf0","#68d2e6","#5ec7db","#54bcd1","#49b1c7","#3fa5bd","#349ab3","#2a8fa9","#20849e","#157994","#0b6e8a"],
  runs: [[[1,"▄▄▄▄▄▄▄▄▄▄"],[2,"▄"],[1,"▄▄▄▄▄▄▄▄"]],[[1,"█████████"],[2,"▀█"],[1,"████████"]],[[3,"▀▀▀▀▀▀▀▀▄"],[2,"██████████"]],[[4,"█"],[3,"██████████"],[4,"█"]],[[5,"▄█"],[4,"██████████"],[5,"▀"]],[[4,"▄██████████"],[5,"█"]],[[6,"▄█"],[5,"██████████▀"]],[[6,"▄███████████"],[7,"▀"]],[[8,"█"],[7,"██████████"],[8,"█"]],[[8,"▄"],[7,"███████████"],[8,"▀"]],[[8,"▄██████████"],[9,"█"]],[[9,"██████████▀"]],[[10,"█████████"],[11,"▀▄"],[10,"█████████"]],[[10,"▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀"]]],
  lines: [
    "▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",
    "█████████▀█████████",
    "▀▀▀▀▀▀▀▀▄██████████",
    "████████████",
    "▄███████████▀",
    "▄███████████",
    "▄███████████▀",
    "▄███████████▀",
    "████████████",
    "▄███████████▀",
    "▄███████████",
    "██████████▀",
    "█████████▀▄█████████",
    "▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
  ],
}
const kimiArt: ArtEntry = {
  color: "#ffe1a0",
  colors: ["#ffe1a0","#f8d793","#f2ce85","#ebc478","#e4ba6a","#ddb05d","#d7a74f","#d09d42","#c99334","#c28927","#bc8019","#b5760c"],
  runs: [[[1,"▄██"],[0,"███"],[1,"██"],[0,"▄▄"]],[[2,"▄██"],[1,"▄▄"],[2,"▄▀"],[1,"▀▀"],[2,"█"],[1,"████"],[2,"█▄"]],[[2,"▄█"],[1,"████████"],[2,"█"],[1,"▄▄"],[2,"▄▀"],[1,"▀▀"],[2,"█"],[1,"█"],[2,"▄"]],[[2,"▀"],[3,"█"],[2,"█████████████▀"]],[[3,"▄▄"],[4,"▄▀"],[3,"▀▀"],[4,"█"],[3,"███████▄▄"],[4,"▄"]],[[4,"█████"],[5,"██"],[4,"▄▄"],[5,"▄▀▀"],[4,"▀▀"],[5,"█"],[4,"█████"],[5,"█"]],[[4,"███████████"],[5,"█▀"],[4,"▀▀"],[5,"█"]],[[6,"▀"],[5,"▀▀"],[6,"█"],[5,"███████▄"],[6,"▄▄"]],[[6,"█"],[7,"█"],[6,"▄▄"],[7,"▄▀"],[6,"▀▀"],[7,"█"],[6,"██████"],[7,"█"],[6,"▄▄"],[7,"▄"]],[[7,"███████"],[8,"█"],[7,"▄"],[8,"▄▀"],[7,"▀▀"],[8,"██"],[7,"████"]],[[7,"█████████"],[8,"▀"],[7,"▀"]],[[9,"▄▀"],[8,"▀▀"],[9,"█"],[8,"█████"],[9,"█"],[8,"▄▄"],[9,"▄"]],[[9,"███"],[10,"█"],[9,"▄▄"],[10,"▄▀"],[9,"▀▀"],[10,"█"],[9,"█████"],[10,"██"],[9,"▄▄"]],[[11,"▀"],[10,"███████"],[11,"█▀"],[10,"▀▀"],[11,"██"],[10,"█"],[11,"▀"]],[[10,"▀"],[11,"█"],[10,"█████▄"],[11,"▄"]],[[11,"▀▀███████▀"]]],
  lines: [
    "▄███████▄▄",
    "▄██▄▄▄▀▀▀██████▄",
    "▄██████████▄▄▄▀▀▀██▄",
    "▀██████████████▀",
    "▄▄▄▀▀▀████████▄▄▄",
    "███████▄▄▄▀▀▀▀███████",
    "████████████▀▀▀█",
    "▀▀▀████████▄▄▄",
    "██▄▄▄▀▀▀████████▄▄▄",
    "████████▄▄▀▀▀██████",
    "█████████▀▀",
    "▄▀▀▀███████▄▄▄",
    "████▄▄▄▀▀▀████████▄▄",
    "▀████████▀▀▀███▀",
    "▀██████▄▄",
    "▀▀███████▀",
  ],
}
const grokArt: ArtEntry = {
  color: "#f2f4f7",
  colors: ["#f2f4f7","#e6e8ec","#d9dce1","#cdd1d7","#c1c5cc","#b5b9c1","#a8adb6","#9ca1ab","#9095a0","#848a96","#777e8b","#6b7280"],
  runs: [[[2,"▄"],[1,"▄▄"],[2,"█████"],[1,"▄▄"],[2,"▄"]],[[3,"▄"],[2,"▄█████"],[3,"█████"],[2,"██"],[3,"█"],[2,"▀"],[3,"▀▄"],[2,"▄"]],[[4,"▄█"],[3,"███▀"],[4,"▀▄█"],[3,"██"]],[[5,"▄"],[4,"███▀▄"],[5,"█"],[4,"████"]],[[4,"███"],[5,"▀"],[4,"▄█▀"],[5,"▀▀"],[4,"██"]],[[5,"██"],[6,"█▄"],[5,"▄▀"],[6,"▀█"],[5,"█"]],[[6,"██"],[7,"█▄▀▀█"],[6,"█"]],[[7,"███"],[8,"█"],[7,"█"]],[[8,"█"],[7,"██"],[8,"█▄▄█"],[7,"██"]],[[8,"███▀"],[9,"▄█"],[8,"███▀"]],[[10,"██▀▄"],[9,"▄▄▄▄▄▄▄▄▄"],[10,"█"],[9,"████▀"]],[[10,"▀▀"],[11,"█"],[10,"███████"],[11,"█"],[10,"▀▀"],[11,"▀"]]],
  lines: [
    "▄▄▄█████▄▄▄",
    "▄▄█████████████▀▀▄▄",
    "▄████▀▀▄███",
    "▄███▀▄█████",
    "███▀▄█▀▀▀██",
    "███▄▄▀▀██",
    "███▄▀▀██",
    "█████",
    "████▄▄███",
    "███▀▄████▀",
    "██▀▄▄▄▄▄▄▄▄▄▄█████▀",
    "▀▀█████████▀▀▀",
  ],
}
const qwenArt: ArtEntry = {
  color: "#9d8df7",
  colors: ["#9d8df7","#9383eb","#8879de","#7e70d2","#7466c6","#6a5cba","#5f52ad","#5548a1","#4b3e95","#413589","#362b7c","#2c2170"],
  runs: [[[1,"▄▄▄▄"]],[[2,"█▀"],[1,"████"],[2,"▄"]],[[2,"██"],[1,"███▄▄▄▄▄▄▄▄"]],[[3,"█▄"],[2,"█████████████"]],[[4,"▀▀▀▀"],[3,"▀▀▀▀▀▀▀▀▀▀▀▀▀▀"]],[[4,"▄"],[5,"▄"]],[[4,"█▄▄▄▄▄▄▄▄▄"],[5,"█"]],[[5,"██"],[6,"█▀"],[5,"██████"],[6,"▀▀"]],[[6,"███"],[7,"█▀"],[6,"████"],[7,"▀"],[6,"▄"]],[[8,"█"],[7,"██████"],[8,"▀█"],[7,"██"],[8,"▄"]],[[8,"█"],[7,"████"],[8,"█▀█"],[7,"█████"]],[[8,"███▀▀▀▀█████"],[9,"██"]],[[10,"█"],[9,"█"],[10,"▀█"],[9,"███"],[10,"▀"]],[[11,"▀▀▀▀▀▀▀▀▄▄"],[10,"████▀"]],[[11,"▀▄▄"],[10,"████"],[11,"▀"]],[[11,"▀▀▀▀▀"]]],
  lines: [
    "▄▄▄▄",
    "█▀████▄",
    "█████▄▄▄▄▄▄▄▄",
    "█▄█████████████",
    "▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
    "▄▄",
    "█▄▄▄▄▄▄▄▄▄█",
    "███▀██████▀▀",
    "████▀████▀▄",
    "███████▀███▄",
    "██████▀██████",
    "███▀▀▀▀███████",
    "██▀████▀",
    "▀▀▀▀▀▀▀▀▄▄████▀",
    "▀▄▄████▀",
    "▀▀▀▀▀",
  ],
}
const minimaxArt: ArtEntry = {
  color: "#fc8cac",
  colors: ["#fc8cac","#f081a1","#e57796","#d96c8b","#cd6180","#c25675","#b64c6a","#ab415f","#9f3654","#932b49","#88213e","#7c1633"],
  runs: [[[1,"▄▄▄▄▄▄"],[2,"▄"],[1,"▄▄▄▄▄▄"],[2,"▄"]],[[2,"█"],[1,"██▀"],[2,"▀▀█"],[1,"██▄"],[2,"█"],[1,"██▀"],[2,"▀▀"],[1,"▀██"]],[[2,"███████████"]],[[3,"███████████"]],[[4,"█▄███████████"]],[[4,"██"],[5,"█"],[4,"███████████"]],[[5,"██"],[6,"█"],[5,"███████████"]],[[6,"██"],[7,"█"],[6,"███████████"]],[[7,"██"],[8,"█"],[7,"███████████"]],[[7,"██"],[8,"█"],[7,"███"],[8,"██"],[7,"▀█████"]],[[8,"██"],[9,"█"],[8,"███"],[9,"▄▄"],[8,"███"],[9,"█"],[8,"█"]],[[9,"██"],[10,"█"],[9,"▄▄▄▄██▀██████"]],[[11,"▀▀"],[10,"▀▀"],[11,"▀▀"],[10,"███"],[11,"▄▄"],[10,"███"]],[[11,"▀"],[10,"▀▀▀▀▀▀"],[11,"▀"]]],
  lines: [
    "▄▄▄▄▄▄▄▄▄▄▄▄▄▄",
    "███▀▀▀███▄███▀▀▀▀██",
    "███████████",
    "███████████",
    "█▄███████████",
    "██████████████",
    "██████████████",
    "██████████████",
    "██████████████",
    "████████▀█████",
    "██████▄▄█████",
    "███▄▄▄▄██▀██████",
    "▀▀▀▀▀▀███▄▄███",
    "▀▀▀▀▀▀▀▀",
  ],
}
const openaiArt: ArtEntry = {
  color: "#5be3c4",
  colors: ["#5be3c4","#54d7b9","#4dcaae","#46bea3","#3fb298","#38a68d","#309981","#298d76","#22816b","#1b7560","#146855","#0d5c4a"],
  runs: [[[0,"▄"],[1,"█"],[0,"██"],[1,"██"],[0,"▄"]],[[1,"▄"],[2,"█"],[1,"▀"],[2,"█"],[1,"█"],[2,"█"],[1,"███"],[2,"█"],[1,"▄"]],[[2,"██▄"],[1,"▄█▀"],[2,"▀"],[1,"▀█▄"]],[[2,"▄▄█▄█▀"],[3,"▀▄"],[2,"▄"],[3,"▄█"]],[[3,"▀"],[4,"▀"],[3,"██"],[4,"▄"],[3,"▄"],[4,"██"],[3,"▀▀█▄"],[4,"▄█"]],[[4,"██"],[5,"▄"],[4,"▄"],[5,"██"],[4,"█▄"],[5,"▄▀"],[4,"▀█"],[5,"█"]],[[4,"██"],[5,"█"],[4,"▀"],[5,"▀██"],[4,"▄"],[5,"▄▀"]],[[5,"█"],[6,"▄"],[5,"██▀"],[6,"██"],[5,"▄"]],[[6,"▀"],[7,"██"],[6,"▄███"]],[[7,"▄▀"],[8,"██"],[7,"▄▄"],[8,"█"],[7,"██"]],[[8,"███"],[7,"▄▀██"],[8,"█"],[7,"▀"],[8,"▀"],[7,"██"]],[[9,"█"],[8,"▀"],[9,"██"],[8,"▄"],[9,"██"],[8,"▀██"],[9,"█"],[8,"▄"]],[[9,"█"],[10,"▀"],[9,"▀▄"],[10,"█"],[9,"█▀█▀"],[10,"▀"]],[[11,"▀"],[10,"█▄"],[11,"▄▄█"],[10,"█▀"],[11,"▀██"]],[[10,"▀▀"],[11,"█"],[10,"█"],[11,"██"],[10,"██"],[11,"▄▄"],[10,"▄"],[11,"█"],[10,"▀"]],[[11,"▀▀███▀▀"]]],
  lines: [
    "▄█████▄",
    "▄█▀███████▄",
    "██▄▄█▀▀▀█▄",
    "▄▄█▄█▀▀▄▄▄█",
    "▀▀██▄▄██▀▀█▄▄█",
    "██▄▄███▄▄▀▀██",
    "███▀▀██▄▄▀",
    "█▄██▀██▄",
    "▀██▄███",
    "▄▀██▄▄███",
    "███▄▀███▀▀██",
    "█▀██▄██▀███▄",
    "█▀▀▄██▀█▀▀",
    "▀█▄▄▄██▀▀██",
    "▀▀██████▄▄▄█▀",
    "▀▀███▀▀",
  ],
}
const geminiArt: ArtEntry = {
  color: "#8fb4ff",
  colors: ["#8fb4ff","#85aaf7","#7a9fef","#7095e7","#668bdf","#5b80d7","#5176ce","#466bc6","#3c61be","#3257b6","#274cae","#1d42a6"],
  runs: [[[1,"█"]],[[2,"█"],[1,"█"],[2,"█"]],[[3,"▄"],[2,"███"],[3,"▄"]],[[4,"▄"],[3,"█████"],[4,"▄"]],[[4,"▄███████"],[5,"█"]],[[4,"▄███████████▄"]],[[5,"▄"],[6,"█"],[5,"███████████████"],[6,"█"],[5,"▄"]],[[6,"▀"],[7,"█"],[6,"███████████████"],[7,"█"],[6,"▀"]],[[7,"▀███████████▀"]],[[8,"█"],[7,"███████"],[8,"█"]],[[9,"▀"],[8,"█████"],[9,"▀"]],[[10,"▀"],[9,"███▀"]],[[11,"█"],[10,"█"],[11,"█"]],[[10,"█"]]],
  lines: [
    "█",
    "███",
    "▄███▄",
    "▄█████▄",
    "▄████████",
    "▄███████████▄",
    "▄█████████████████▄",
    "▀█████████████████▀",
    "▀███████████▀",
    "█████████",
    "▀█████▀",
    "▀███▀",
    "███",
    "█",
  ],
}
const claudeArt: ArtEntry = {
  color: "#f2a488",
  colors: ["#f2a488","#e79b7f","#dd9175","#d2886c","#c77f63","#bc765a","#b26c50","#a76347","#9c5a3e","#915135","#87472b","#7c3e22"],
  runs: [[[0,"█"],[1,"█"],[0,"▄"]],[[1,"██"],[2,"▄█"],[1,"█"]],[[1,"▀██"],[2,"█"],[1,"█"],[2,"█"],[1,"█"],[2,"█"]],[[3,"██▄█"],[2,"█"],[3,"█"],[2,"██"],[3,"█"],[2,"██"],[3,"▀"]],[[4,"▀"],[3,"██"],[4,"█▄█"],[3,"█▄█"],[4,"▀▄"],[3,"███"],[4,"▀"]],[[4,"▀██"],[5,"█▄"],[4,"██"],[5,"▄"],[4,"█"],[5,"▄"],[4,"███"]],[[4,"▀"],[5,"█"],[4,"████████"],[5,"▄▄"],[4,"▄"]],[[5,"▄▄"],[6,"▄▄▄▀"],[5,"██████████"],[6,"█"],[5,"▀"]],[[6,"▀▀▀▀▀▀▀██████"],[7,"██▄"]],[[7,"▄"],[8,"█"],[7,"██████"],[8,"█"],[7,"▀▀"],[8,"█"],[7,"██"]],[[8,"▄"],[7,"▄█"],[8,"█▀"],[7,"▄"],[8,"██"],[7,"████▄"]],[[9,"█"],[8,"█▀"],[9,"▀███▀"],[8,"▀█"],[9,"█"],[8,"▀█"],[9,"▄"]],[[9,"▀"],[10,"██"],[9,"█"],[10,"█"],[9,"█▄▀▄"]],[[10,"█"],[11,"█▄"],[10,"█▀█"],[11,"▄▀"]],[[11,"▀"],[10,"▀"],[11,"█"],[10,"█▀"],[11,"▀"]],[[11,"██"]]],
  lines: [
    "██▄",
    "██▄██",
    "▀███████",
    "██▄████████▀",
    "▀███▄██▄█▀▄███▀",
    "▀███▄██▄█▄███",
    "▀█████████▄▄▄",
    "▄▄▄▄▄▀███████████▀",
    "▀▀▀▀▀▀▀████████▄",
    "▄████████▀▀███",
    "▄▄██▀▄██████▄",
    "██▀▀███▀▀██▀█▄",
    "▀█████▄▀▄",
    "██▄█▀█▄▀",
    "▀▀██▀▀",
    "██",
  ],
}
const mistralArt: ArtEntry = {
  color: "#ff9455",
  colors: ["#ff9455","#f3894d","#e77f46","#db743e","#cf6a36","#c35f2e","#b65527","#aa4a1f","#9e4017","#92350f","#862b08","#7a2000"],
  runs: [[[1,"▄▄▄▄▄▄▄▄"]],[[2,"████████"]],[[3,"████▄▄▄▄"],[4,"▄▄"],[3,"▄▄▄▄████"]],[[4,"█████████"],[5,"█"],[4,"████████"]],[[4,"█████████"],[5,"█"],[4,"████████"]],[[5,"██████████████████████"]],[[6,"██████████████████████"]],[[7,"████"],[8,"▀"],[7,"████"],[8,"▀"],[7,"████"]],[[7,"████████████"]],[[8,"████"],[9,"█"],[8,"▄▄▄▄▀▀▀▀"],[9,"▄"],[8,"▄▄▄▄████"]],[[9,"█████████"],[10,"█"],[9,"████████"]],[[10,"▀▀▀▀▀▀▀▀▀"],[11,"▀"],[10,"▀▀▀▀▀▀▀▀"]]],
  lines: [
    "▄▄▄▄▄▄▄▄",
    "████████",
    "████▄▄▄▄▄▄▄▄▄▄████",
    "██████████████████",
    "██████████████████",
    "██████████████████████",
    "██████████████████████",
    "████▀████▀████",
    "████████████",
    "█████▄▄▄▄▀▀▀▀▄▄▄▄▄████",
    "██████████████████",
    "▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
  ],
}
const nvidiaArt: ArtEntry = {
  color: "#a9e24d",
  colors: ["#a9e24d","#9cd546","#90c73f","#83ba38","#77ac31","#6a9f2a","#5e9123","#51841c","#457615","#38690e","#2c5b07","#1f4e00"],
  runs: [[[2,"████████████"]],[[4,"▄"],[3,"▄"],[4,"▄▀▀"],[3,"▀▀"],[4,"█"],[3,"███████"]],[[5,"▄"],[4,"▄"],[5,"█"],[4,"▀"],[5,"▀██"],[4,"▄"],[5,"▄"],[4,"▀█████"]],[[4,"▄"],[5,"██▄"],[4,"▄"],[5,"█▀▀"],[4,"▀█▄▀███"]],[[5,"███"],[6,"█"],[5,"█"],[6,"▄▄█"],[5,"█"],[6,"▀▄█"],[5,"██"]],[[6,"▀█"],[7,"▄▀"],[6,"█"],[7,"▄"],[6,"██"],[7,"█"],[6,"█▀▄█"],[7,"█"],[6,"▀▀"]],[[8,"▀"],[7,"█▄"],[8,"▀███"],[7,"▀▀"],[8,"▀▄█"],[7,"█▀"],[8,"▀"]],[[7,"▀█▄"],[8,"▄"],[7,"▄▄"],[8,"██"],[7,"▀"],[8,"▀▄"],[7,"▄"],[8,"█"]],[[9,"▀"],[8,"▀"],[9,"█▀▄▄"],[8,"▄▄"],[9,"█"],[8,"████"]],[[9,"████████████"]]],
  lines: [
    "████████████",
    "▄▄▄▀▀▀▀████████",
    "▄▄█▀▀██▄▄▀█████",
    "▄██▄▄█▀▀▀█▄▀███",
    "█████▄▄██▀▄███",
    "▀█▄▀█▄████▀▄██▀▀",
    "▀█▄▀███▀▀▀▄██▀▀",
    "▀█▄▄▄▄██▀▀▄▄█",
    "▀▀█▀▄▄▄▄█████",
    "████████████",
  ],
}
const stepfunArt: ArtEntry = {
  color: "#9dc4ff",
  colors: ["#9dc4ff","#90b8f5","#84abea","#779fe0","#6a93d5","#5e86cb","#517ac0","#456db6","#3861ab","#2b55a1","#1f4896","#123c8c"],
  runs: [[[1,"▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄"]],[[2,"███████████████████"]],[[3,"███████████████████"]],[[4,"██████"],[5,"▀▀▀▀▀▀▀▀▀▀▀▀▀"]],[[4,"██████"]],[[5,"██████"]],[[6,"██████"],[7,"▄▄▄▄▄▄▄▄▄"]],[[7,"██████"],[8,"█"],[7,"█████"],[8,"█▀▀▀"]],[[7,"▄▄▄██████"],[8,"█"],[7,"█████"],[8,"█"]],[[8,"█████████"],[9,"█"],[8,"█████"],[9,"█"]],[[9,"█████████"],[10,"█"],[9,"█████"],[10,"█"]],[[10,"▀▀▀▀▀▀▀▀▀"],[11,"█"],[10,"█████"],[11,"█"]],[[11,"█"],[10,"█████"],[11,"█"]],[[11,"▀▀▀▀▀▀▀"]]],
  lines: [
    "▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",
    "███████████████████",
    "███████████████████",
    "██████▀▀▀▀▀▀▀▀▀▀▀▀▀",
    "██████",
    "██████",
    "██████▄▄▄▄▄▄▄▄▄",
    "█████████████▀▀▀",
    "▄▄▄█████████████",
    "████████████████",
    "████████████████",
    "▀▀▀▀▀▀▀▀▀███████",
    "███████",
    "▀▀▀▀▀▀▀",
  ],
}
const tencentArt: ArtEntry = {
  color: "#6fb7ff",
  colors: ["#6fb7ff","#66acf3","#5da1e7","#5596db","#4c8bcf","#4380c3","#3a74b6","#3169aa","#285e9e","#205392","#174886","#0e3d7a"],
  runs: [[[2,"██▄"]],[[1,"████▄"]],[[3,"▄▄▄▄▄▄▄"],[2,"██████▄"],[3,"▄"]],[[3,"███████████████"],[4,"█▄"]],[[5,"▀"],[4,"█████████████████▄"]],[[4,"▀▀▀▀▀█████▀▀▀▀▀▀▀▀"]],[[5,"████"],[6,"█"]],[[7,"█"],[6,"████"]],[[7,"█████"]],[[7,"████"],[8,"█"]],[[9,"▄"],[8,"████"],[9,"▀"]],[[9,"█████"]],[[10,"████"],[11,"█"]],[[10,"████"],[11,"▀"]],[[11,"▀▀▀▀"]]],
  lines: [
    "██▄",
    "████▄",
    "▄▄▄▄▄▄▄██████▄▄",
    "████████████████▄",
    "▀█████████████████▄",
    "▀▀▀▀▀█████▀▀▀▀▀▀▀▀",
    "█████",
    "█████",
    "█████",
    "█████",
    "▄████▀",
    "█████",
    "█████",
    "████▀",
    "▀▀▀▀",
  ],
}
const bytedanceArt: ArtEntry = {
  color: "#5ec8ff",
  colors: ["#5ec8ff","#57bdf4","#4fb2e8","#48a7dd","#409cd2","#3991c6","#3185bb","#2a7aaf","#226fa4","#1b6499","#13598d","#0c4e82"],
  runs: [[[2,"▄█"]],[[3,"█▄█"],[2,"█"]],[[3,"█"],[4,"██"],[3,"█"]],[[4,"█"],[5,"██"],[4,"█"]],[[4,"█"],[5,"█▄"],[4,"▄▄"],[5,"██"],[4,"█"]],[[5,"█"],[6,"█"],[5,"████"],[6,"█"],[5,"█"]],[[6,"█"],[7,"█"],[6,"██"],[7,"██▄"],[6,"████"],[7,"█"],[6,"█"]],[[7,"█"],[8,"█"],[7,"████"],[8,"█"],[7,"████"],[8,"█"],[7,"█"]],[[7,"█"],[8,"█"],[7,"████"],[8,"█"],[7,"████"],[8,"█"],[7,"█"]],[[8,"█"],[9,"█"],[8,"████"],[9,"█"],[8,"████"],[9,"█"],[8,"█"]],[[9,"█"],[10,"█"],[9,"████"],[10,"▀"],[9,"▀▀"],[10,"█"],[9,"█"]],[[10,"▀"],[11,"▀"],[10,"███"],[11,"██"],[10,"█"]],[[11,"▀▀"],[10,"▀"]]],
  lines: [
    "▄█",
    "█▄██",
    "████",
    "████",
    "██▄▄▄███",
    "████████",
    "██████▄██████",
    "█████████████",
    "█████████████",
    "█████████████",
    "██████▀▀▀██",
    "▀▀██████",
    "▀▀▀",
  ],
}
const opencodeArt: ArtEntry = {
  color: "#9fe8c8",
  colors: ["#9fe8c8","#93dbbc","#87cfb0","#7bc2a5","#6fb599","#63a88d","#569c81","#4a8f75","#3e8269","#32755e","#266952","#1a5c46"],
  runs: [[[1,"▄▄▄▄▄▄▄▄▄▄"]],[[1,"██████████"]],[[2,"██████████"]],[[3,"████"]],[[4,"████"]],[[4,"████"]],[[5,"████"]],[[6,"████"]],[[7,"████"]],[[7,"████"]],[[8,"████"]],[[9,"██████████"]],[[10,"██████████"]],[[10,"▀▀▀▀▀▀▀▀▀▀"]]],
  lines: [
    "▄▄▄▄▄▄▄▄▄▄",
    "██████████",
    "██████████",
    "████",
    "████",
    "████",
    "████",
    "████",
    "████",
    "████",
    "████",
    "██████████",
    "██████████",
    "▀▀▀▀▀▀▀▀▀▀",
  ],
}


type ArtRegistry = {
  models: Record<string, ArtEntry>
  providers: Record<string, ArtEntry>
  default: ArtEntry
}

const registry: ArtRegistry = {
  models: {
    // opencode first-party
    "opencode/big-pickle": opencodeArt,
    // DeepSeek family (model IDs like deepseek/deepseek-v4-flash on tokenrouter)
    "tokenrouter/deepseek/*": deepseekArt,
    "deepseek/*": deepseekArt,
    // GLM (z-ai org)
    "tokenrouter/z-ai/glm-5*": zaiArt,
    "tokenrouter/z-ai/*": zaiArt,
    "z-ai/*": zaiArt,
    "glm*": zaiArt,
    // Kimi
    "tokenrouter/moonshotai/*": kimiArt,
    "moonshotai/*": kimiArt,
    "kimi*": kimiArt,
    // Grok
    "tokenrouter/x-ai/*": grokArt,
    "x-ai/*": grokArt,
    "grok*": grokArt,
    // Qwen
    "tokenrouter/qwen/*": qwenArt,
    "qwen/*": qwenArt,
    "qwen*": qwenArt,
    // MiniMax
    "tokenrouter/minimax/*": minimaxArt,
    "minimax/*": minimaxArt,
    "MiniMax*": minimaxArt,
    "minimax*": minimaxArt,
    // OpenAI
    "tokenrouter/openai/*": openaiArt,
    "openai/*": openaiArt,
    "gpt*": openaiArt,
    // Anthropic/Claude
    "anthropic/*": claudeArt,
    "anthropic/claude*": claudeArt,
    "claude*": claudeArt,
    // Google
    "google/*": geminiArt,
    "gemini*": geminiArt,
    // Mistral
    "mistralai/*": mistralArt,
    "mistral/*": mistralArt,
    "devstral*": mistralArt,
    // NVIDIA
    "tokenrouter/nvidia/*": nvidiaArt,
    "nvidia/*": nvidiaArt,
    "nemotron*": nvidiaArt,
    // Xiaomi MiMo
    "tokenrouter/xiaomi/*": opencodeArt,
    "xiaomi/*": opencodeArt,
    "mimo*": opencodeArt,
    // ByteDance Seed
    "seed-2*": bytedanceArt,
    // StepFun
    "tokenrouter/stepfun/*": stepfunArt,
    "stepfun/*": stepfunArt,
    "step-*": stepfunArt,
    // Sakana
    "tokenrouter/sakana/*": bytedanceArt,
    "sakana/*": bytedanceArt,
    "fugu*": bytedanceArt,
    // Tencent
    "tokenrouter/tencent/*": tencentArt,
    "tencent/*": tencentArt,
    // Miromind
    "tokenrouter/miromind/*": opencodeArt,
    "miromind/*": opencodeArt,
  },
  providers: {
    deepseek: deepseekArt,
    "z-ai": zaiArt,
    zai: zaiArt,
    moonshotai: kimiArt,
    moonshot: kimiArt,
    "x-ai": grokArt,
    xai: grokArt,
    grok: grokArt,
    qwen: qwenArt,
    alibaba: qwenArt,
    minimax: minimaxArt,
    openai: openaiArt,
    anthropic: claudeArt,
    google: geminiArt,
    mistralai: mistralArt,
    mistral: mistralArt,
    nvidia: nvidiaArt,
    xiaomi: opencodeArt,
    stepfun: stepfunArt,
    sakana: bytedanceArt,
    tencent: tencentArt,
    miromind: opencodeArt,
    bytedance: bytedanceArt,
    opencode: opencodeArt,
  },
  default: opencodeArt,
}

// ---------------------------------------------------------------------------
// FIGlet-style fallback fonts for unknown models (name rendered as art).
// 5-row block fonts for A-Z, 0-9. Lowercase maps to uppercase.
// ---------------------------------------------------------------------------

const FONT: Record<string, string[]> = {
  A: ["███╗   ██╗", "████╗ ██║", "██╔█████║", "██║╚██╔╝", "██║ ╚═╝ "],
  B: ["██████╗ ", "██╔══██╗", "██████╔╝", "██╔══██╗", "██████╔╝", "╚═════╝ "].slice(0, 5),
  C: ["██████╗", "██╔═══╝", "██║   ", "██║   ", "╚██████╗", " ╚═════╝"].slice(0, 5),
  D: ["██████╗ ", "██╔═██╗ ", "██║ ██║ ", "██║ ██║ ", "██████╔╝", "╚═════╝ "].slice(0, 5),
  E: ["███████╗", "██╔════╝", "█████╗  ", "██╔══╝  ", "███████╗", "╚══════╝"].slice(0, 5),
  F: ["███████╗", "██╔════╝", "█████╗  ", "██╔══╝  ", "██║     ", "╚═╝     "].slice(0, 5),
  G: [" ██████╗ ", "██╔════╝ ", "██║  ███╗", "██║   ██║", "╚██████╔╝", " ╚═════╝ "].slice(0, 5),
  H: ["██╗  ██╗", "██║  ██║", "███████║", "██╔══██║", "██║  ██║", "╚═╝  ╚═╝"].slice(0, 5),
  I: ["██╗", "██║", "██║", "██║", "██║", "╚═╝"].slice(0, 5),
  J: ["     ██╗", "     ██║", "     ██║", "██╗  ██║", "╚█████╔╝", " ╚════╝ "].slice(0, 5),
  K: ["██╗  ██╗", "██║ ██╔╝", "█████╔╝ ", "██╔██╗  ", "██║╚██╗ ", "╚═╝ ╚═╝ "].slice(0, 5),
  L: ["██╗   ", "██║   ", "██║   ", "██║   ", "██████╗", "╚═════╝"].slice(0, 5),
  M: ["███╗   ███╗", "████╗ ████║", "██╔████╔██║", "██║╚██╔╝██║", "██║ ╚═╝ ██║", "╚═╝     ╚═╝"].slice(0, 5),
  N: ["███╗   ██╗", "████╗  ██║", "██╔██╗ ██║", "██║╚████║", "██║ ╚███║", "╚═╝  ╚══╝"].slice(0, 5),
  O: [" ██████╗ ", "██╔═══██╗", "██║   ██║", "██║   ██║", "╚██████╔╝", " ╚═════╝ "].slice(0, 5),
  P: ["██████╗ ", "██╔══██╗", "██████╔╝", "██╔═══╝ ", "██║    ", "╚═╝    "].slice(0, 5),
  Q: [" ██████╗ ", "██╔═══██╗", "██║   ██║", "██║  ██╔╝", "╚█████╔╝", " ╚═════╝"].slice(0, 5),
  R: ["██████╗ ", "██╔══██╗", "██████╔╝", "██╔══██╗", "██║  ██║", "╚═╝  ╚═╝"].slice(0, 5),
  S: ["███████╗", "██╔════╝", "██████╗ ", "╚═══██║", "██████╔╝", "╚═════╝ "].slice(0, 5),
  T: ["████████╗", "╚══██╔══╝", "   ██║   ", "   ██║   ", "   ╚═╝   ", "        "].slice(0, 5),
  U: ["██╗   ██╗", "██║   ██║", "██║   ██║", "██║   ██║", "╚██████╔╝", " ╚═════╝ "].slice(0, 5),
  V: ["██╗   ██╗", "██║   ██║", "██║   ██║", "╚██╗ ██╔╝", " ╚████╔╝ ", "  ╚═══╝  "].slice(0, 5),
  W: ["██╗    ██╗", "██║    ██║", "██║ ███╗██║", "██║██╔╝██║", "╚█╣█╔╝ █╣╝", " ╚╝╚═╝ ╚═╝"].slice(0, 5),
  X: ["██╗  ██╗", "╚██╗██╔╝", " ╚███╔╝ ", " ██╔██╗ ", "██╔╝╚██╗", "╚═╝  ╚═╝"].slice(0, 5),
  Y: ["██╗   ██╗", "╚██╗ ██╔╝", " ╚████╔╝ ", "  ╚██╔╝  ", "   ██║   ", "   ╚═╝   "].slice(0, 5),
  Z: ["███████╗", "╚══██╔═╝", "   ██║  ", "  ██╔╝  ", " █████╔╝", " ╚════╝ "].slice(0, 5),
  "0": [" █████╗ ", "██╔═██╗ ", "██║ ██║ ", "╚█▄█╔╝ ", " ╚═╝  ", "      "].slice(0, 5),
  "1": [" ██╗", "███║", "╚██║", " ██║", " ██║", " ╚═╝"].slice(0, 5),
  "2": ["██████╗ ", "╚══██╔╝", "   ██║  ", "  ██╔╝ ", " █████╔╝", "╚═════╝ "].slice(0, 5),
  "3": ["██████╗", "╚═══██║", " █████║", " ╚═══██║", "██████╔╝", "╚═════╝"].slice(0, 5),
  "4": ["██╗  ██╗", "██║  ██║", "███████║", "╚═══██║", "    ██║", "    ╚═╝"].slice(0, 5),
  "5": ["███████╗", "██╔════╝", "██████╗ ", "╚════██║", "██████╔╝", "╚═════╝ "].slice(0, 5),
  "6": [" █████╗ ", "██╔═══╝ ", "██████╗ ", "██╔══██║", "╚██████╔╝", " ╚═════╝ "].slice(0, 5),
  "7": ["███████╗", "╚════██║", "   ██╔╝", "  ██║  ", "  ╚═╝  ", "       "].slice(0, 5),
  "8": [" █████╗ ", "██╔═██╗ ", "╚█▄▄█╔╝ ", " ▄▄█▄▄  ", " █████╔╝", " ╚════╝ "].slice(0, 5),
  "9": [" █████╗ ", "██╔═██╗ ", "╚█████╔╝", " ╚═══██║", " █████╔╝", " ╚════╝ "].slice(0, 5),
  ".": ["  ", "  ", "  ", "  ", "▄▄", "▀▀"].slice(0, 5),
  "-": ["      ", "      ", "██████", "      ", "      "],
  "_": ["    ", "    ", "    ", "    ", "▀▀▀▀", "▄▄▄▄"].slice(0, 5),
}

// Render a short label as FIGlet-block art (max 12 chars; then truncates).
function figlet(label: string): { lines: string[]; width: number } {
  const raw = label.toUpperCase().replace(/[^A-Z0-9.\-_ ]/g, "").slice(0, 12)
  const chars = Array.from(raw)
  const rows = ["", "", "", "", ""]
  let width = 0
  for (const ch of chars) {
    const glyph = FONT[ch] ?? FONT["-"]
    const glyphRows = glyph.length > 5 ? glyph : [...glyph, ...Array(5 - glyph.length).fill("")]
    for (let i = 0; i < 5; i++) rows[i] += (glyphRows[i] ?? "") + " "
    width += (glyphRows[0]?.length ?? 0) + 1
  }
  return { lines: rows, width }
}

// Match art for a model, with the fallback chain: exact → glob → provider → default.
function matchArt(providerID: string, modelID: string, displayName: string): { entry: ArtEntry; name: string } {
  const full = `${providerID}/${modelID}`
  // 1. exact + glob model keys
  const modelKeys = [full, modelID, `${providerID}/*`]
  for (const key of modelKeys) {
    const direct = registry.models[key]
    if (direct) return { entry: direct, name: nameFor(displayName, modelID) }
    if (key.endsWith("*")) {
      const prefix = key.slice(0, -1)
      for (const [pattern, entry] of Object.entries(registry.models)) {
        if (pattern.startsWith(prefix) && pattern.endsWith("*")) {
          const target = pattern.slice(0, -1)
          if (full.startsWith(target) || modelID.startsWith(target)) {
            return { entry, name: nameFor(displayName, modelID) }
          }
        }
      }
    }
  }
  // Glob-model keys where pattern prefix matches full id (e.g. deepseek/*, glm*)
  for (const [pattern, entry] of Object.entries(registry.models)) {
    if (!pattern.endsWith("*")) continue
    const target = pattern.slice(0, -1)
    if (full.startsWith(target) || modelID.startsWith(target)) {
      return { entry, name: nameFor(displayName, modelID) }
    }
  }
  // 2. provider keys
  const providerKey = providerID.toLowerCase()
  const byProvider = registry.providers[providerKey]
  if (byProvider) return { entry: byProvider, name: nameFor(displayName, modelID) }
  // provider substring (z-ai in glm-5.3, etc.)
  const brand = Object.keys(registry.providers).find(
    (key) => providerKey.includes(key) || modelID.toLowerCase().includes(key),
  )
  if (brand) return { entry: registry.providers[brand]!, name: nameFor(displayName, modelID) }
  // 3. FIGlet of the display name in a soft brand color (unknown models)
  const name = nameFor(displayName, modelID)
  const fig = figlet(name.replace(/[^A-Za-z0-9.\-_ ]/g, "").slice(0, 12))
  return {
    entry: { lines: fig.lines, color: "#8888AA", compact: [name] },
    name,
  }
}

// Brand tokens whose official casing differs from mechanical title-casing.
const BRAND_TOKENS: Record<string, string> = {
  deepseek: "DeepSeek",
  glm: "GLM",
  kimi: "Kimi",
  grok: "Grok",
  qwen: "Qwen",
  minimax: "MiniMax",
  mimo: "MiMo",
  gpt: "GPT",
  openai: "OpenAI",
  claude: "Claude",
  anthropic: "Anthropic",
  gemini: "Gemini",
  mistral: "Mistral",
  devstral: "Devstral",
  nemotron: "Nemotron",
  nvidia: "NVIDIA",
  xiaomi: "Xiaomi",
  seed: "Seed",
  stepfun: "StepFun",
  fugu: "Fugu",
  sakana: "Sakana",
  tencent: "Tencent",
  miromind: "Miromind",
  mirothinker: "MiroThinker",
  moonshot: "Moonshot",
  grok: "Grok",
  muse: "Muse",
  spark: "Spark",
  contributor: "Contributor",
  free: "Free",
  pro: "Pro",
  max: "Max",
  nano: "Nano",
  mini: "Mini",
  flash: "Flash",
  turbo: "Turbo",
  ultra: "Ultra",
  air: "Air",
  lite: "Lite",
  vision: "Vision",
  exp: "Exp",
  omni: "Omni",
  codex: "Codex",
  oss: "OSS",
  bytedance: "ByteDance",
  zai: "Z.ai",
  "z-ai": "Z.ai",
  hy3: "HY3",
  nemotron: "Nemotron",
  lightning: "Lightning",
  highspeed: "HighSpeed",
  her: "HER",
  voxtral: "Voxtral",
  pickle: "Pickle",
  big: "Big",
  xhigh: "xHigh",
}

function nameFor(displayName: string, modelID: string): string {
  const clean = displayName || modelID
  // strip org prefix like "deepseek/deepseek-v4-flash" → "DeepSeek V4 Flash"
  const last = clean.split("/").pop() ?? clean
  const spaced = last.replace(/[-_]/g, " ")
  return spaced
    .split(" ")
    .filter((token) => token.length > 0)
    .map((token) => BRAND_TOKENS[token.toLowerCase()] ?? (token === token.toLowerCase() ? token[0]!.toUpperCase() + token.slice(1) : token))
    .join(" ")
    .trim()
}
// ---------------------------------------------------------------------------
// Color helpers (RGBA from hex; gradient interpolation)
// ---------------------------------------------------------------------------

type RGBA = { r: number; g: number; b: number; a: number }

function hexToRgba(hex: string): RGBA | undefined {
  const value = hex.replace("#", "").trim()
  if (value.length !== 6 && value.length !== 8) return undefined
  const num = Number.parseInt(value, 16)
  if (Number.isNaN(num)) return undefined
  if (value.length === 6) return { r: (num >> 16) & 255, g: (num >> 8) & 255, b: num & 255, a: 255 }
  return { r: (num >>> 24) & 255, g: (num >>> 16) & 255, b: (num >>> 8) & 255, a: num & 255 }
}

function mix(a: RGBA, b: RGBA, t: number): RGBA {
  return {
    r: Math.round(a.r + (b.r - a.r) * t),
    g: Math.round(a.g + (b.g - a.g) * t),
    b: Math.round(a.b + (b.b - a.b) * t),
    a: 255,
  }
}

function toHex(color: RGBA): string {
  const clamp = (value: number) => Math.max(0, Math.min(255, Math.round(value))).toString(16).padStart(2, "0")
  return `#${clamp(color.r)}${clamp(color.g)}${clamp(color.b)}`
}

/** Vertical gradient from brand color toward background (mockup style: dark base, bright crest). */
function gradientStops(brand: RGBA, background: RGBA, rows: number): RGBA[] {
  const stops: RGBA[] = []
  for (let i = 0; i < rows; i++) {
    const t = rows <= 1 ? 1 : i / (rows - 1)
    // bright at the crest (top), fading into the background at the tail
    const lift = 0.35 + 0.65 * (1 - t)
    stops.push(mix(background, brand, Math.min(1, lift)))
  }
  return stops
}

// ---------------------------------------------------------------------------
// Current-model resolution (mirrors tui context/local.tsx fallbackModel)
// ---------------------------------------------------------------------------

type ModelRefLite = { providerID: string; modelID: string }

function parseModel(value: string): ModelRefLite | undefined {
  const index = value.indexOf("/")
  if (index === -1) return { providerID: value, modelID: "" }
  return { providerID: value.slice(0, index), modelID: value.slice(index + 1) }
}

type StatePaths = { readonly path: { readonly state: string } }
type ModelJson = { recent?: Array<{ providerID: string; modelID: string }> }
type FsLike = { existsSync(path: string): boolean; readFileSync(path: string, encoding: "utf8"): string }
type PathLike = { join(...parts: string[]): string }

function readModelJson(state: StatePaths): ModelRefLite | undefined {
  try {
    // Plugins run under Bun: sync require is available at runtime.
    const fs = require("node:fs") as FsLike
    const path = require("node:path") as PathLike
    const file = path.join(state.path.state, "model.json")
    if (!fs.existsSync(file)) return undefined
    const raw = JSON.parse(fs.readFileSync(file, "utf8")) as ModelJson
    const first = raw.recent?.[0]
    return first ? { providerID: first.providerID, modelID: first.modelID } : undefined
  } catch {
    return undefined
  }
}

function isModelValid(providers: ReadonlyArray<{ id: string; models: Record<string, unknown> }>, ref: ModelRefLite | undefined): boolean {
  if (!ref || !ref.modelID) return false
  return providers.some((provider) => provider.id === ref.providerID && provider.models[ref.modelID] !== undefined)
}

function resolveCurrentModel(api: TuiPluginApi, modelTick: () => number, onModelFileChange: () => void): () => ModelRefLite | undefined {
  // Re-read model.json when the model picker or prompt cycle writes it, so the
  // banner swaps live on ctrl+x m switches.
  try {
    const fs = require("node:fs") as FsLike & { watchFile(path: string, listener: () => void): void; unwatchFile(path: string, listener?: () => void): void }
    const path = require("node:path") as PathLike
    const file = path.join(api.state.path.state, "model.json")
    const listener = () => onModelFileChange()
    fs.watchFile(file, { interval: 500 }, listener)
    api.lifecycle.onDispose(() => {
      fs.unwatchFile(file, listener)
    })
  } catch {
    // watch unavailable — banner stays static for this session
  }

  return createMemo(() => {
    modelTick() // dependency: re-resolve when model.json changes
    const providers = api.state.provider
    // 1. config `model` (opencode.json)
    const configModel = api.state.config.model
    if (typeof configModel === "string") {
      const ref = parseModel(configModel)
      if (isModelValid(providers, ref)) return ref
    }
    // 2. last used (state/model.json recent[0]) — matches core fallback chain
    const recent = readModelJson(api.state)
    if (isModelValid(providers, recent)) return recent
    // 3. first provider's default / first model
    const provider = providers[0]
    if (!provider) return undefined
    const firstModel = Object.values(provider.models)[0] as { id?: string } | undefined
    const modelID = firstModel?.id ?? Object.keys(provider.models)[0]
    if (!modelID) return undefined
    return { providerID: provider.id, modelID }
  })
}

function displayName(api: TuiPluginApi, ref: ModelRefLite | undefined): string {
  if (!ref) return ""
  const provider = api.state.provider.find((item) => item.id === ref.providerID)
  const info = provider?.models[ref.modelID] as { name?: string } | undefined
  return info?.name ?? ref.modelID
}

// ---------------------------------------------------------------------------
// Banner components
// ---------------------------------------------------------------------------

function HomeBanner(props: { api: TuiPluginApi; theme: TuiSlotContext["theme"]; ref: () => ModelRefLite | undefined }) {
  const brand = createMemo(() => {
    const ref = props.ref()
    if (!ref) return undefined
    const name = displayName(props.api, ref)
    const matched = matchArt(ref.providerID, ref.modelID, name)
    return { matched, ref, name }
  })

  // Derived entirely from the memo, so a model switch re-renders everything.
  const view = createMemo(() => {
    const value = brand()
    if (!value) return undefined
    const { matched, ref } = value
    const name = matched.name
    const theme = props.theme.current
    const bg = { r: theme.background.r * 255, g: theme.background.g * 255, b: theme.background.b * 255, a: 255 }
    const brandHex = matched.entry.color ?? "#8888AA"
    const brandColor = hexToRgba(brandHex)
    const allLines = matched.entry.lines
    // Generated smooth art: runs+colors. Legacy entries: plain lines.
    const runs: Array<Array<[number, string]>> | undefined = matched.entry.runs
    const palette = matched.entry.colors
    // Cap art height to ~40% of the terminal so the prompt stays visible.
    const maxRows = Math.max(4, Math.floor(props.api.renderer.height * 0.4))
    const keep = (n: number) => {
      if (n <= maxRows) return Array.from({ length: n }, (_, i) => i)
      const step = Math.ceil(n / maxRows)
      return Array.from({ length: n }, (_, i) => i)
        .filter(i => i === 0 || i === n - 1 || i % step !== 0)
    }
    const rowIdx = keep(runs ? runs.length : allLines.length)
    const stops = gradientStops(brandColor ?? { r: 120, g: 120, b: 160, a: 255 }, bg, rowIdx.length)
    return { name, ref, bg, brandColor, brandHex, runs, palette, allLines, rowIdx, stops, maxRows }
  })

  return (
    <Show when={view()}>
      <box flexDirection="column" alignItems="center" flexShrink={1} minHeight={0}>
        <box flexDirection="column" alignItems="center">
          <Index each={view()!.rowIdx}>
            {(row, i) => (
              <box flexDirection="row" flexShrink={0} minHeight={0}>
                {view()!.runs
                  ? (view()!.runs![i] ?? []).map(([ci, text], j) => (
                      <text fg={view()!.palette?.[ci] ?? view()!.brandHex}>{text}</text>
                    ))
                  : <text fg={toHex(view()!.stops[Math.min(i, view()!.stops.length - 1)]!)}>{view()!.allLines[i]}</text>
                }
              </box>
            )}
          </Index>
        </box>
        <box flexDirection="row" gap={1} paddingTop={0}>
          <text fg={toHex(view()!.brandColor ?? { r: 150, g: 150, b: 180, a: 255 })}>{view()!.name}</text>
          <Show when={view()!.ref?.providerID}>
            <text fg={toHex(mix(view()!.bg, view()!.brandColor ?? { r: 120, g: 120, b: 160, a: 255 }, 0.45))}>
              ({view()!.ref?.providerID})
            </text>
          </Show>
        </box>
      </box>
    </Show>
  )
}

// One-line signature glyphs for the compact session banner.
const SESSION_GLYPHS: Record<string, string> = {
  deepseek: "–<}}}}<",
  "z-ai": "◈",
  zai: "◈",
  moonshotai: "☾",
  moonshot: "☾",
  "x-ai": "✦",
  xai: "✦",
  grok: "✦",
  qwen: "∮",
  minimax: "☰",
  openai: "❖",
  anthropic: "❍",
  google: "✧",
  mistralai: "▮▮",
  mistral: "▮▮",
  nvidia: "▲",
  xiaomi: "◉",
  stepfun: "⇉",
  sakana: "≈",
  tencent: "⌬",
  miromind: "❂",
  bytedance: "❖",
  opencode: "⬢",
}

function sessionGlyph(providerID: string, modelID: string): string {
  const key = providerID.toLowerCase()
  if (SESSION_GLYPHS[key]) return SESSION_GLYPHS[key]!
  const brand = Object.keys(SESSION_GLYPHS).find((name) => key.includes(name) || modelID.toLowerCase().includes(name))
  return brand ? SESSION_GLYPHS[brand]! : "◈"
}

function SessionBanner(props: { api: TuiPluginApi; ref: () => ModelRefLite | undefined; sessionID: string }) {
  const brand = createMemo(() => {
    const ref = props.ref()
    if (!ref) return undefined
    // Use the current model (matches the prompt footer, swaps live on switch).
    const raw = displayName(props.api, ref)
    const matched = matchArt(ref.providerID, ref.modelID, raw)
    return { matched, active: ref, name: matched.name }
  })

  // Derived in a memo so model switches re-render (no cached function child).
  const view = createMemo(() => {
    const value = brand()
    if (!value) return undefined
    const { matched, active, name } = value
    const brandColor = hexToRgba(matched.entry.color ?? "#8888AA") ?? { r: 130, g: 130, b: 160, a: 255 }
    const glyph = sessionGlyph(active.providerID, active.modelID)
    return { glyph, name, colorHex: toHex(brandColor) }
  })

  return (
    <Show when={view()}>
      <box flexDirection="row" gap={1} justifyContent="center" flexShrink={0} paddingBottom={0}>
        <text fg={view()!.colorHex}>{view()!.glyph}</text>
        <text fg={view()!.colorHex}>{view()!.name}</text>
      </box>
    </Show>
  )
}

// ---------------------------------------------------------------------------
// Plugin
// ---------------------------------------------------------------------------

const tui: TuiPlugin = async (api) => {
  const [modelFileTick, setModelFileTick] = createSignal(0)
  const ref = resolveCurrentModel(api, modelFileTick, () => setModelFileTick((n) => n + 1))

  api.slots.register({
    order: 0,
    slots: {
      home_logo(ctx: TuiSlotContext) {
        return <HomeBanner api={api} theme={ctx.theme} ref={ref} />
      },
    },
  })

  api.slots.register({
    order: 0,
    slots: {
      session_prompt(ctx, value) {
        const Prompt = api.ui.Prompt
        const Slot = api.ui.Slot
        return (
          <box flexDirection="column" flexShrink={0}>
            <SessionBanner api={api} ref={ref} sessionID={value.session_id} />
            <Prompt
              sessionID={value.session_id}
              visible={value.visible}
              disabled={value.disabled}
              onSubmit={value.on_submit}
              ref={value.ref}
              right={<Slot name="session_prompt_right" session_id={value.session_id} />}
            />
          </box>
        )
      },
    },
  })
}

export default {
  id: "model-banner",
  tui,
}
